Repository nilsjung/chat-application, pull requests merged in 2019-01, with the labels that each got.

#56 Add User Online Status
  app/src/App.js
  app/src/actions/userActions.js
  app/src/api.js
  app/src/components/user/UserInformationField.js
  app/src/config/index.js
  app/src/index.js
  app/src/reducers/index.js
  app/src/reducers/userReducer.js
  app/src/socket/chat.js
  app/src/socket/index.js
  app/src/socket/socket.js
  app/src/store/index.js
  backend/socket/messages.js
  backend/socket/onlinestatus.js
  backend/socket/socket.js
Labels: backend, frontend, issue

#60 Added wait script for backend to wait for mongoDB to be ready
  backend/app.js
  backend/dockerfile
  docker-compose.yaml
Labels: bugfix

#79 Documentation
  ProjectDocumentation.pdf
  authors.txt
  documentation/documentation.out
  documentation/documentation.tex
  documentation/documentation.toc
  documentation/img/chat.png
  documentation/img/chatCommunication.png
  documentation/img/components.png
  documentation/img/dataModel.png
  documentation/img/redux.png
  documentation/img/settings.png
  documentation/parts/abstract.tex
  documentation/parts/appendix.tex
  documentation/parts/conclusion.tex
  documentation/parts/discussion.tex
  documentation/parts/introduction.tex
  documentation/parts/methods.tex
  documentation/parts/results.tex
  documentation/parts/table_matrix.tex
  documentation/parts/table_user-stories.tex
Labels: must-be-implemented
